Repository wuwendell/MinecraftManhunt, pull requests merged in 2020-12, with the labels that each got.

#1 Implement Command Handling for /hunters and /runners
  README.md
  out/MinecraftManhunt.jar
  src/plugin.yml
  src/us/wendell/MinecraftManhunt/CommandOptions.java
  src/us/wendell/MinecraftManhunt/HelperMethods.java
  src/us/wendell/MinecraftManhunt/HuntersCommand.java
  src/us/wendell/MinecraftManhunt/MinecraftManhunt.java
  src/us/wendell/MinecraftManhunt/RunnersCommand.java
Labels: enhancement, good first issue

#2 Implement Event Listeners for compass tracking
  README.md
  out/MinecraftManhunt.jar
  src/us/wendell/MinecraftManhunt/HelperMethods.java
  src/us/wendell/MinecraftManhunt/HuntersCommand.java
  src/us/wendell/MinecraftManhunt/MinecraftManhunt.java
  src/us/wendell/MinecraftManhunt/RunnersCommand.java
Labels: enhancement

#5 Change types from hashset to set
  src/us/wendell/MinecraftManhunt/HelperMethods.java
  src/us/wendell/MinecraftManhunt/HuntersCommand.java
  src/us/wendell/MinecraftManhunt/MinecraftManhunt.java
  src/us/wendell/MinecraftManhunt/RunnersCommand.java
Labels: good first issue, refactor

#7 Handle player quit and joins; update player gamemodes when switching …
  out/MinecraftManhunt.jar
  src/us/wendell/MinecraftManhunt/HuntersCommand.java
  src/us/wendell/MinecraftManhunt/MinecraftManhunt.java
  src/us/wendell/MinecraftManhunt/RunnersCommand.java
Labels: bug, refactor
